add_lunch_combo merk_hammerhead-userdebug
add_lunch_combo merk_p3100-userdebug
add_lunch_combo merk_jactiveltexx-userdebug
add_lunch_combo merk_mako-userdebug
add_lunch_combo merk_i9100-userdebug
add_lunch_combo merk_i9300-userdebug
